### ISSUE TITLE
How to add the theme

### ISSUE THREAD

**Issue by initialjj** [mrkdyrit/OneDarkPro-Tabby#1]
I can't find a config file to add this theme. Could you please tell me the file name to add? Thank you.

**Comment by mrkdyrit** [comment]
Hello, you may add the color scheme directly to your config file by copying  the contents of [config.yml](https://github.com/mrkdyrit/OneDarkPro-Tabby/blob/main/config.yaml) and pasting it to your config.yml file.

You may refer to the [wiki](https://github.com/Eugeny/tabby/wiki/Config-file) to locate your config file.

**Comment by initialjj** [comment]
Thanks a lot.

**Comment by mrkdyrit** [comment]
No problem. I'll be closing the issue now.
